/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Advertise: typeof import('./src/components/Advertise.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeroDialog: typeof import('./src/components/HeroDialog.vue')['default']
    HeroModel: typeof import('./src/components/HeroModel.vue')['default']
    HeroView: typeof import('./src/components/HeroView.vue')['default']
    MapDialog: typeof import('./src/components/MapDialog.vue')['default']
    MapEdit: typeof import('./src/components/MapEdit.vue')['default']
    MapLand: typeof import('./src/components/MapLand.vue')['default']
    MapModel: typeof import('./src/components/MapModel.vue')['default']
    MapPreview: typeof import('./src/components/MapPreview.vue')['default']
    MapView: typeof import('./src/components/MapView.vue')['default']
    Model: typeof import('./src/components/Model.vue')['default']
    Modules: typeof import('./src/components/Modules.vue')['default']
    ResourceModel: typeof import('./src/components/resourceModel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skills: typeof import('./src/components/Skills.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
  }
}
