/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Advertise: typeof import('./../components/Advertise.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    HeroDialog: typeof import('./../components/HeroDialog.vue')['default']
    HeroView: typeof import('./../components/HeroView.vue')['default']
    MapDialog: typeof import('./../components/MapDialog.vue')['default']
    MapEdit: typeof import('./../components/MapEdit.vue')['default']
    MapLand: typeof import('./../components/MapLand.vue')['default']
    MapPreview: typeof import('./../components/MapPreview.vue')['default']
    MapView: typeof import('./../components/MapView.vue')['default']
    Modules: typeof import('./../components/Modules.vue')['default']
    ResourceModel: typeof import('./../components/resourceModel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skills: typeof import('./../components/Skills.vue')['default']
    TextEditor: typeof import('./../components/TextEditor.vue')['default']
    ThemeToggle: typeof import('./../components/ThemeToggle.vue')['default']
  }
}
